var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.Symbol=function(){var a=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+a++}}();$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};
$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var g=a[d];g in b||(b[g]={});b=b[g]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,b){var d=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var c=d.length,f=a.length;b=Math.max(0,Math.min(b|0,d.length));for(var e=0;e<f&&b<c;)if(d[b++]!=a[e++])return!1;return e>=f}},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,b){var d=this;d instanceof String&&(d=String(d));var c=d.length;b=b||0;for(0>b&&(b=Math.max(b+c,0));b<c;b++){var f=d[b];if(f===a||Object.is(f,a))return!0}return!1}},"es7","es3");$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");
(function(a,c){"object"===typeof exports&&"object"===typeof module?module.exports=c():"function"===typeof define&&define.amd?define("WeAssert",[],c):"object"===typeof exports?exports.WeAssert=c():a.WeAssert=c()})(this,function(){return function(a){function c(d){if(b[d])return b[d].exports;var g=b[d]={i:d,l:!1,exports:{}};a[d].call(g.exports,g,g.exports,c);g.l=!0;return g.exports}var b={};c.m=a;c.c=b;c.d=function(a,b,f){c.o(a,b)||Object.defineProperty(a,b,{enumerable:!0,get:f})};c.r=function(a){$jscomp.initSymbol();
$jscomp.initSymbol();"undefined"!==typeof Symbol&&Symbol.toStringTag&&($jscomp.initSymbol(),Object.defineProperty(a,Symbol.toStringTag,{value:"Module"}));Object.defineProperty(a,"__esModule",{value:!0})};c.t=function(a,b){b&1&&(a=c(a));if(b&8||b&4&&"object"===typeof a&&a&&a.__esModule)return a;var d=Object.create(null);c.r(d);Object.defineProperty(d,"default",{enumerable:!0,value:a});if(b&2&&"string"!=typeof a)for(var e in a)c.d(d,e,function(h){return a[h]}.bind(null,e));return d};c.n=function(a){var b=
a&&a.__esModule?function(){return a["default"]}:function(){return a};c.d(b,"a",b);return b};c.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};c.p="/";return c(c.s=1)}([function(a,c,b){function d(a){return a&&"substitution"!=a.action&&"literal"!=a.action?null==a.action?d(a.args[0]):{action:a.action,args:a.args.map(d)}:a}function g(a){return"substitution"==a.action||"literal"==a.action?a.args[0]:"negation"==a.action?"substitution"==a.args[0].action?"!"+a.args[0].args[0]:"(!"+g(a.args[0])+
")":"conjunction"==a.action?"("+g(a.args[0])+" & "+g(a.args[1])+")":"disjunction"==a.action?"("+g(a.args[0])+" | "+g(a.args[1])+")":"implication"==a.action?"("+g(a.args[0])+" -> "+g(a.args[1])+")":"equivalence"==a.action?"("+g(a.args[0])+" <-> "+g(a.args[1])+")":""}var f=b(4),e=b(5);Array.prototype.peek=function(){return this[this.length-1]};Array.prototype.includes||(Array.prototype.includes=function(a,b){var h=Object(this),c=parseInt(h.length)||0;if(0===c)return!1;b=parseInt(b)||0;0<=b||(b=c+b,
0>b&&(b=0));for(var n;b<c;){n=h[b];if(a===n||a!==a&&n!==n)return!0;b++}return!1});String.prototype.startsWith||(String.prototype.startsWith=function(a,b){b=b||0;return this.indexOf(a,b)===b});a.exports.negate=function(a){return{action:"negation",args:[a]}};a.exports.treeToExpr=g;a.exports.proofToString=function(a){a=a.map(function(a){return"sep"==a.label?"------------------------------\n":a.tree?a.idx+"\t"+a.tree+"\t"+a.label+"\n":a.label+"\n"});return a.join("")};a.exports.buildTree=function(a){return d(f.parse(e.lex(a)))}},
function(a,c,b){c.__esModule=!0;var d=b(2),g=function(){},f={0:"DEBUG",1:"WARN",2:"ERROR"},e=function(a){switch(a){case "DEBUG":return 0;case "WARN":return 1;case "ERROR":return 2}throw Error();};c["default"]={checkVulcan:function(){return d},build:function(){var a=2,b={},c=[],t={define:{type:function(a,b){}},assume:function(a){c.push(a)},setLevel:function(b){b=e(b);if(0==b||1==b||2==b)a=b;else throw Error("we-assert: invalid error level");},getLevel:function(){return f[a]},checkIsProved:function(a){a=
d.prove(c,a);return d.isProofComplete(a)},setHandler:function(a){g=a},getProposition:function(a){return b[a]},defineProposition:function(a,c){b[a]=c},assert:{that:function(a,b){a||g(b);return 1==a},proposition:function(a,b){t.defineProposition(a,b);var d=b[2];(b=b[0].apply(void 0,b[1]))&&c.push(a);return this.that(b,d)},thatIsProved:function(a,b){(a=t.checkIsProved(a))||g(b);return a},forXBetween:function(a,b){var c=this.that;return{that:function(d,h){for(var e=a;e<b;e++)c(d(e),h)}}},atLevel:function(b){var c=
this.that;return{that:function(d,h){e(b)>=a&&c(d,h)}}}}};return t}}},function(a,c,b){function d(a){var b=[],c=function(a){a&&("negation"==a.action&&"substitution"==a.args[0].action?b.push("!"+a.args[0].args[0]):"substitution"==a.action?b.push(a.args[0]):(c(a.args[0]),c(a.args[1])))};c(a);return b}function g(a,b){a=d(a);b=d(b);var c=function(a,b){var c=[];a.forEach(function(a){var d=a.startsWith("!")?a.substring(1):a;a=a.startsWith("!")?a.substring(1):"!"+a;b.includes(a)&&c.push(d)});return c}(a,b);
if(1<c.length)return{action:"literal",args:[!0]};b=a.concat(b);b.sort();b=b.filter(function(a){a=a.startsWith("!")?a.substring(1):a;return c.includes(a)?!1:!0}).reduce(function(a,b){return a.peek()==b?a:a.concat([b])},[]);return 0==b.length?{action:"literal",args:[!1]}:e.buildTree(b.join(" | "))}var f=b(3),e=b(0);a.exports.prove=function(a,b){var c=[],d=[],h=0;a.forEach(function(a){a=f.convertToCNF(e.buildTree(a)).map(function(a){a.idx=h++;return a});d=d.concat(a);c.push(d)});var m=h,k=c.map(function(a){return a.peek()}).map(function(a){return f.splitClauses(a.tree).map(function(b){b.idx=
h++;b.from=a.idx;return b})}).reduce(function(a,b){return a.concat(b)},[]);k.forEach(function(a){d.push({label:"knowledge base clause from "+a.from,tree:a,idx:a.idx})});a=f.convertToCNF(e.negate(e.buildTree(b)));a.peek();f.splitClauses(a.peek().tree).forEach(function(a){a.idx=h++;k.push(a);d.push({label:"assume for a contradiction",tree:k.peek(),idx:k.peek().idx})});var u=function(a){var b=[a],r=d.filter(function(b){return b.idx==a})[0];if(!r.req)return b;r.req.forEach(function(a){b=b.concat(u(a))});
return b};for(a={};;){b=[];for(var q=0;q<k.length;q++)for(var l={},r=1;r<k.length;l={$jscomp$loop$prop$req$2:l.$jscomp$loop$prop$req$2},r++){var p=g(k[q],k[r]);if(!b.map(e.treeToExpr).includes(e.treeToExpr(p))){p.idx=h++;d.push({label:"resolve of "+k[q].idx+" and "+k[r].idx,tree:p,idx:p.idx,req:[k[q].idx,k[r].idx]});if("literal"==p.action&&0==p.args[0])return l.$jscomp$loop$prop$req$2=u(p.idx),d.filter(function(a){return function(b){return a.$jscomp$loop$prop$req$2.includes(b.idx)||b.idx<=m||"sep"==
b.label}}(l)).map(function(a){a.tree&&(a.tree=e.treeToExpr(a.tree));return a});"literal"==p.action&&1==p.args[0]||b.push(p)}}a.$jscomp$loop$prop$kbS$4=k.map(e.treeToExpr);if(b.map(e.treeToExpr).every(function(a){return function(b){return a.$jscomp$loop$prop$kbS$4.includes(b)}}(a)))return d.push({label:"model exhausted, proof could not be reached"}),d.map(function(a){a.tree&&(a.tree=e.treeToExpr(a.tree));return a});k=k.concat(b);a={$jscomp$loop$prop$kbS$4:a.$jscomp$loop$prop$kbS$4}}};a.exports.addParens=
function(a){return e.treeToExpr(e.buildTree(a))};a.exports.isProofComplete=function(a){return"model exhausted, proof could not be reached"!=a.peek().label}},function(a,c,b){function d(a,b){return{action:"conjunction",args:[a,b]}}function g(a,b){return{action:"implication",args:[a,b]}}function f(a){return{action:"negation",args:[a]}}function e(a,b){return{action:"disjunction",args:[a,b]}}function h(a){return a&&"substitution"!=a.action&&"literal"!=a.action?"equivalence"==a.action?d(g(h(a.args[0]),
h(a.args[1])),g(h(a.args[1]),h(a.args[0]))):{action:a.action,args:a.args.map(h)}:a}function m(a){if(!a||"substitution"==a.action||"literal"==a.action)return a;if("negation"==a.action){if("disjunction"==a.args[0].action)return m(d(f(a.args[0].args[0]),f(a.args[0].args[1])));if("conjunction"==a.args[0].action)return m(e(f(a.args[0].args[0]),f(a.args[0].args[1])))}return{action:a.action,args:a.args.map(m)}}function v(a){return a&&"substitution"!=a.action&&"literal"!=a.action?"implication"==a.action?
e(f(v(a.args[0])),v(a.args[1])):{action:a.action,args:a.args.map(v)}:a}function t(a){return a&&"substitution"!=a.action&&"literal"!=a.action?"negation"==a.action&&"negation"==a.args[0].action?t(a.args[0].args[0]):{action:a.action,args:a.args.map(t)}:a}function n(a){return JSON.parse(JSON.stringify(a))}function w(a){if(!a||"substitution"==a.action||"literal"==a.action)return a;if("disjunction"==a.action){if("conjunction"==a.args[1].action)return w(d(e(n(a.args[0]),n(a.args[1].args[0])),e(n(a.args[0]),
n(a.args[1].args[1]))));if("conjunction"==a.args[0].action)return w(d(e(n(a.args[1]),n(a.args[0].args[0])),e(n(a.args[1]),n(a.args[0].args[1]))))}return{action:a.action,args:a.args.map(w)}}function k(a){if(!a||"substitution"==a.action||"literal"==a.action)return a;if("disjunction"==a.action){var b=a.args[0],c=a.args[1];if("negation"==b.action&&l.treeToExpr(b.args[0])==l.treeToExpr(c)||"negation"==c.action&&l.treeToExpr(c.args[0])==l.treeToExpr(b))return{action:"literal",args:[!0]}}return"conjunction"==
a.action&&(b=a.args[0],c=a.args[1],"negation"==b.args[0].action&&l.treeToExpr(b.args[0].args[0])==l.treeToExpr(c)||"negation"==c.args[0].action&&l.treeToExpr(c.args[0].args[0])==l.treeToExpr(b))?{action:"literal",args:[!1]}:{action:a.action,args:a.args.map(k)}}function u(a){if(!a||"substitution"==a.action||"literal"==a.action)return a;if("disjunction"==a.action){var b=a.args[0],c=a.args[1];if("literal"==b.action){if(1==b.args[0])return b;if(0==b.args[0])return c}if("literal"==c.action){if(1==c.args[0])return c;
if(0==c.args[0])return b}}if("conjunction"==a.action){b=a.args[0];c=a.args[1];if("literal"==b.action){if(1==b.args[0])return c;if(0==b.args[0])return b}if("literal"==c.action){if(1==c.args[0])return b;if(0==c.args[0])return c}}return{action:a.action,args:a.args.map(u)}}function q(a){var b=function(a){if(2>a.args.length||"implication"==a.action||"equivalence"==a.action||"disjunction"==a.action)return!1;var d="conjunction"==a.args[0].action?b(a.args[0]):c(a.args[0]);return"conjunction"==a.args[1].action?
b(a.args[1])&&d:c(a.args[1])&&d},c=function(a){return a?"substitution"==a.action||"literal"==a.action?!0:"conjunction"==a.action?!1:"negation"==a.action?"substitution"==a.args[0].action:"disjunction"==a.action?c(a.args[0]&&a.args[1]):!1:!1};return"substitution"==a.action||"negation"==a.action&&"substitution"==a.args[0].action?!0:b(a)}var l=b(0);a.exports.convertToCNF=function(a){a=[{label:"initial expression",tree:a}];for(var b=$jscomp.makeIterator([{task:"eliminate bijection",f:h},{task:"eliminate implication",
f:v},{task:"DeMorgan's",f:m},{task:"eliminate double negation",f:t},{task:"distribute or over and",f:w},{task:"complementation",f:k},{task:"identity",f:u}]),c=b.next();!c.done;c=b.next()){c=c.value;if(q(a.peek().tree))break;for(;;){var d=c.f(a.peek().tree);if(l.treeToExpr(d)==l.treeToExpr(a.peek().tree))break;a.push({label:c.task,tree:d})}}return a};a.exports.isCNF=q;a.exports.splitClauses=function(a){var b=[],c=function(a){"conjunction"==a.action?(c(a.args[0]),c(a.args[1])):b.push(a)};c(a);return b}},
function(a,c){a.exports.parse=function(a){function b(d){d=d||null;for(var e=[];f=a.shift();)if("boundary"==f.type)if("("==f.value)e.push(b());else{if(")"==f.value)break}else if("variable"==f.type){if(e.push(c("substitution",[f.value])),"!"===d)break}else if("operator"==f.type)if("!"===f.value)e.push(b(f.value));else{if(d){var g=e.slice(0);e=[];e.push(c(d,g))}d=f.value}return c(d,e)}function c(a,b){return{action:{"!":"negation","|":"disjunction","&":"conjunction","->":"implication","<->":"equivalence"}[a]||
a,args:b}}var f;return b()}},function(a,c){a.exports.lex=function(a){function b(a,b){e.push({type:a,value:b})}function c(a,b){throw Error('Unrecognized token "'+a+'" on position '+b+"!");}for(var f=0,e=[],h,m="";h=a[f++];)/[<>\-|&!]/.test(h)?(m+=h,-1!==["!","|","&","->","<->"].indexOf(m)&&(b("operator",m),m="")):(m.length&&c(m,f-m.length-1),/\s/.test(h)||(/[A-Za-z]/.test(h)?b("variable",h.toUpperCase()):/[\(\)]/.test(h)?b("boundary",h):c(h,f-2)));return e}}])});
